name: .NET

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.6
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: NuGet Restore  
      run: nuget restore 
      
    - name: Build
      run: dotnet build --no-restore2
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
